CREATE TABLE jwt_refresh_entity
(
    id           BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    username     VARCHAR(255)                            NOT NULL,
    refresh      VARCHAR(512)                            NOT NULL,
    created_date TIMESTAMP WITHOUT TIME ZONE,
    CONSTRAINT pk_jwt_refresh_entity PRIMARY KEY (id)
);

CREATE TABLE users
(
    id              BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    username        VARCHAR(255)                            NOT NULL UNIQUE,
    status          VARCHAR(50)                             NOT NULL DEFAULT 'ACTIVE',
    signup_provider VARCHAR(50),
    role_type       VARCHAR(50)                             NOT NULL,
    nickname        VARCHAR(255),
    email           VARCHAR(255),
    created_date    TIMESTAMP WITHOUT TIME ZONE,
    updated_date    TIMESTAMP WITHOUT TIME ZONE,
    CONSTRAINT pk_users PRIMARY KEY (id)
);